<a href="https://colab.research.google.com/github/PatchareepornT/bsc_dpdm22/blob/main/Classification_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_digits
digits = load_digits()

import matplotlib.pyplot as plt
import numpy as np

import pandas as pd
from sklearn.model_selection import train_test_split

# Quiz 3 march

* แบ่ง data ออกเป็น 80(train) 20(test) โดยใช้ random_state = 9
* หา parameters ที่ดีที่สุด (K(1,3,5) Distance_weighted(yes/no)) ด้วย 10-fold-cross-validation
* test parameters ที่ดีที่สุด กับ test data

In [ ]:
digits

In [ ]:
X = digits['data']

y = digits['target']

In [ ]:
print(X)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [ ]:
X_test_0 = X[1400:]
X_train_0 = X[:1400]

In [ ]:
y_test_0 = X[1400:]
y_train_0 = X[:1400]

In [ ]:
X_test_0

In [ ]:
X_df = pd.DataFrame(y)

In [ ]:
X_df

0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=42)

In [ ]:
X_train, X_test, y_train, y_test

(array([[ 0.,  0.,  3., ..., 13.,  4.,  0.],
        [ 0.,  0.,  9., ...,  3.,  0.,  0.],
        [ 0.,  0.,  0., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  9., ..., 16.,  2.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  1.,  0.,  0.]]),
 array([[ 0.,  0.,  0., ..., 14.,  5.,  0.],
        [ 0.,  0., 11., ...,  1.,  0.,  0.],
        [ 0.,  0.,  8., ...,  8.,  0.,  0.],
        ...,
        [ 0.,  0.,  7., ..., 10.,  0.,  0.],
        [ 0.,  0.,  7., ..., 16.,  4.,  0.],
        [ 0.,  0., 14., ...,  5.,  0.,  0.]]),
 array([6, 0, 0, ..., 2, 7, 1]),
 array([6, 9, 3, 7, 2, 1, 5, 2, 5, 2, 1, 9, 4, 0, 4, 2, 3, 7, 8, 8, 4, 3,
        9, 7, 5, 6, 3, 5, 6, 3, 4, 9, 1, 4, 4, 6, 9, 4, 7, 6, 6, 9, 1, 3,
        6, 1, 3, 0, 6, 5, 5, 1, 9, 5, 6, 0, 9, 0, 0, 1, 0, 4, 5, 2, 4, 5,
        7, 0, 7, 5, 9, 5, 5, 4, 7, 0, 4, 5, 5, 9, 9, 0, 2, 3, 8, 0, 6, 4,
        4, 9, 1, 2, 8, 3, 5, 2, 9, 0, 4, 4, 4, 3, 5, 3, 1, 3, 5, 9, 4, 2,
        7, 7, 4, 4, 1, 9, 2