<a href="https://colab.research.google.com/github/PatchareepornT/bsc_dpdm22/blob/main/Classification_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_digits
digits = load_digits()

import matplotlib.pyplot as plt
import numpy as np

import pandas as pd
from sklearn.model_selection import train_test_split

# Quiz 3 march

* แบ่ง data ออกเป็น 80(train) 20(test) โดยใช้ random_state = 9
* หา parameters ที่ดีที่สุด (K(1,3,5) Distance_weighted(yes/no)) ด้วย 10-fold-cross-validation
* test parameters ที่ดีที่สุด กับ test data

In [2]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [3]:
X = digits['data']

y = digits['target']

In [4]:
print(X)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [5]:
X_test_0 = X[1400:]
X_train_0 = X[:1400]

In [6]:
y_test_0 = X[1400:]
y_train_0 = X[:1400]

In [7]:
X_test_0

array([[ 0.,  0.,  7., ..., 16., 16.,  6.],
       [ 0.,  0.,  8., ...,  1.,  0.,  0.],
       [ 0.,  0., 11., ..., 13., 16.,  7.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [8]:
X_df = pd.DataFrame(y)

In [9]:
X_df

0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=8)

In [11]:
X_train, X_test, y_train, y_test

(array([[ 0.,  0., 10., ..., 12.,  4.,  0.],
        [ 0.,  0.,  9., ..., 15.,  4.,  0.],
        [ 0.,  0.,  0., ...,  7.,  0.,  0.],
        ...,
        [ 0.,  0.,  3., ...,  0.,  0.,  0.],
        [ 0.,  0.,  7., ..., 10., 13.,  3.],
        [ 0.,  0.,  0., ..., 12.,  4.,  0.]]),
 array([[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0., 15., ..., 13.,  6.,  0.],
        [ 0.,  0.,  6., ..., 11.,  2.,  0.],
        ...,
        [ 0.,  0.,  7., ..., 10.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.]]),
 array([0, 5, 4, ..., 9, 2, 6]),
 array([6, 8, 1, 5, 0, 9, 0, 1, 1, 6, 7, 8, 9, 5, 8, 4, 7, 2, 5, 3, 3, 2,
        4, 0, 1, 3, 8, 9, 7, 7, 7, 0, 3, 7, 8, 9, 2, 1, 6, 3, 2, 1, 7, 4,
        8, 9, 6, 8, 8, 2, 6, 0, 5, 9, 8, 9, 3, 4, 3, 7, 5, 5, 6, 7, 1, 8,
        3, 0, 7, 1, 6, 1, 7, 3, 3, 6, 9, 0, 1, 7, 1, 9, 3, 0, 7, 8, 0, 9,
        8, 7, 7, 5, 5, 7, 9, 4, 5, 3, 5, 9, 0, 3, 1, 0, 8, 8, 3, 0, 5, 5,
        1, 6, 6, 0, 9, 6, 9